import type { MenuItem } from "@/lib/types";

const timestamp = new Date(0).toISOString();

export const fallbackMenuItems: MenuItem[] = [
  {
    id: "seed-pollo",
    name: "Pollo a la parrilla",
    slug: "pollo-a-la-parrilla",
    description: "Char-grilled chicken with rice, crisp potatoes, salad, and house vinaigrette.",
    price_nok: 219,
    category: "Grill",
    image_path: "/images/polloalaparrila.jpg",
    image_alt: "Grilled chicken plate with rice, potatoes, and salad",
    featured: true,
    active: true,
    sort_order: 10,
    created_at: timestamp,
    updated_at: timestamp,
  },
  {
    id: "seed-lomo",
    name: "Peruvian lomo saltado",
    slug: "peruvian-lomo-saltado",
    description: "A hot pan classic with tender beef, vegetables, potatoes, rice, and bright Peruvian flavor.",
    price_nok: 239,
    category: "Peruvian",
    image_path: "/images/lomosaltado.jpg",
    image_alt: "Peruvian lomo saltado served with rice and potatoes",
    featured: true,
    active: true,
    sort_order: 20,
    created_at: timestamp,
    updated_at: timestamp,
  },
  {
    id: "seed-empanadas",
    name: "Peruvian empanadas",
    slug: "peruvian-empanadas",
    description: "Golden pastry with a savory filling, served as a weekend favorite when available.",
    price_nok: 89,
    category: "Specials",
    image_path: "/images/empanadas.jpg",
    image_alt: "Freshly baked Peruvian empanadas on a plate",
    featured: true,
    active: true,
    sort_order: 30,
    created_at: timestamp,
    updated_at: timestamp,
  },
  {
    id: "seed-empanada",
    name: "Single empanada",
    slug: "single-empanada",
    description: "A warm pastry for the table, crisp outside and deeply seasoned inside.",
    price_nok: 49,
    category: "Small plates",
    image_path: "/images/empanada.jpg",
    image_alt: "Single golden empanada with garnish",
    featured: false,
    active: true,
    sort_order: 40,
    created_at: timestamp,
    updated_at: timestamp,
  },
  {
    id: "seed-torta",
    name: "Torta tres leches",
    slug: "torta-tres-leches",
    description: "Soft milk cake with a delicate finish for a calm, sweet close to dinner.",
    price_nok: 95,
    category: "Dessert",
    image_path: "/images/torta3leches.jpg",
    image_alt: "Slice of torta tres leches dessert",
    featured: false,
    active: true,
    sort_order: 50,
    created_at: timestamp,
    updated_at: timestamp,
  },
];
